import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: "https://https://www.virtualifyme.com/",
      priority: 1.0,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/accelarations",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/accelarations/application-modernization",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/accelarations/applied-ai",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/accelarations/blockchain",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/industries",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/industries/agritech",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/industries/healthtech",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/industries/fintech",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/industries/edtech",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/industries/retail",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/industries/banking",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/industries/news-media",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/industries/insurance",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/industries/public-services",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/industries/travel",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/industries/logistics",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/industries/real-estate",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/industries/energy",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/industries/telecom",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/industries/entertainment",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/industries/social-media",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/industries/advertising",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/services",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/services/web",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/services/mobile",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/services/uiux-design",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/services/cloud",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/services/augumented-virtual-reality-arvr",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/services/seo",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/services/testing",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/services/analytics",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/services/internet-of-things-iot",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/services/blockchain",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/services/web-3.0",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/services/artifical-intelligence-machine-learning-aiml",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/services/metaverse",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/services/big-data",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/technologies",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/technologies/web-apps",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/technologies/mobile-apps",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/technologies/native-apps",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/technologies/smart-tv-apps",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/technologies/progressive-web-apps-pwa",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/technologies/serverless-applications",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/technologies/single-page-applications-spa",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/technologies/microservices",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/technologies/cloud-native-applications",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/products",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/products/vsc-travelcrafter",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/products/benzmint",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/products/vsc-smart-training",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/products/dashview-pro",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/products/vsc-parkingpulse",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/innovation",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/innovation/blockchain-parking-platform",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/what-we-do/innovation/iot-smart-training",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/about-us",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/about-us/vsc-vision",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/about-us/vsc-mission",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/about-us/vsc-values",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/about-us/vsc-culture",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/about-us/vsc-goals",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/about-us/vsc-events",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/leadership",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/leadership/our-beliefs",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/leadership/board-of-directors",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/leadership/management-team",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/leadership/leadership-team",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/prespective",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/prespective/optimizing-it-costs",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/prespective/enterprise-mobility",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/prespective/digital-enterprise",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/prespective/agile-imperatives",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/prespective/smarter-faster-lighter-enterprises",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/accelarations/engineering-services",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/accelarations/generative-ai",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/accelarations/quality-engineering",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/way-we-work",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/way-we-work/tech-driven-innovation",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/way-we-work/deep-industry-expertise",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/way-we-work/excellence-in-execution",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/who-we-are/way-we-work/investing-in-people",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/travelcrafter",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/travelcrafter/traveler-classification",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/travelcrafter/accommodation",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/travelcrafter/food-preferences",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/travelcrafter/attraction-details",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/travelcrafter/crypto-payments",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/travelcrafter/personalized-itinerary",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/synthworkforce",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/synthworkforce/talent-acquisition",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/synthworkforce/payroll",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/synthworkforce/employee-engagement",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/synthworkforce/digitally-connected-workforce",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/synthworkforce/talent-performance",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/synthworkforce/employee-retention",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/ledgerchain",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/ledgerchain/blockchain",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/ledgerchain/cryptocurrency",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/ledgerchain/smart-contracts",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/ledgerchain/decentralized-applications",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/ledgerchain/crypto-wallet",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/ledgerchain/crypto-exchange",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/trainsync",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/trainsync/online-training",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/trainsync/offline-training",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/trainsync/live-training",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/trainsync/recorded-training",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/trainsync/training-management",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/trainsync/applicant-engagement",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/smartspot",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/smartspot/smart-parking",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/smartspot/parking-management",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/smartspot/crypto-payments",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/smartspot/parking-guidance",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/smartspot/parking-analytics",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
    {
      url: "https://https://www.virtualifyme.com/upcoming-projects/smartspot/pre-reservations",
      priority: 0.8,
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
  ];
}
